### ISSUE TITLE
 请问这个cas插件到底要怎么用？

### ISSUE THREAD

**Issue by eden214** [wsfe/yapi-plugin-cas#1]
LOGIN_SERVER和AUTH_SERVER有什么区别？哪个才是直接跳转的？我司的cas只提供了一个地址怎么办？

**Comment by angrytoro** [comment]
那就填写一模一样的

**Comment by eden214** [comment]
@angrytoro 折腾了几天无果。。可能跟我司的cas不兼容吧23333

**Comment by angrytoro** [comment]
l泪奔

**Comment by jmcdjyu** [comment]
Readme.MD中"AUTH_SERVER" : "https://cas.example.com/cas/serviceValidate"这句少了最后一个逗号
